language: node_js
node_js:
  - "12"

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.83.1/hugo_0.83.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm install -g firebase-tools
script:
 - echo "Deploy To Firebase CI"
 - make build
after_success:
  - firebase deploy --only hosting --project pulumi-hugo-cn --token $FIREBASE_TOKEN